#!/usr/bin/env bash
set -euo pipefail

cd ~

# Validate arguments
if [ "$#" -ne 1 ]; then
    echo "Error: You did not supply enough arguments"
    exit 1
fi

# Symlinks
ln -s "$1/.config/emacs" .emacs.d
ln -s "$1/.ssh" .ssh
ln -s "$1/.config/git/config" .gitconfig

# Fish
sudo usermod --shell /usr/bin/fish "$USER"
mkdir -p .config/fish

# Nix
mkdir -p .config/nix
echo 'experimental-features = nix-command flakes' >> .config/nix/nix.conf
sudo systemctl enable nix-daemon
sudo systemctl start nix-daemon

# VTerm
echo '
if test "$INSIDE_EMACS" = "vterm"
    and set -q EMACS_VTERM_PATH
    and test -f "$EMACS_VTERM_PATH/etc/emacs-vterm.fish"
    source "$EMACS_VTERM_PATH/etc/emacs-vterm.fish"
end
' >> .config/fish/config.fish

# Direnv
echo 'direnv hook fish | source' >> .config/fish/config.fish

# Emacs
distrobox-export --app emacs
