#!/bin/bash
set -euo pipefail

cd ~

# Symlinks
ln -s "$DISTROBOX_HOST_HOME/.config/emacs" .emacs.d
ln -s "$DISTROBOX_HOST_HOME/.ssh" .ssh
ln -s "$DISTROBOX_HOST_HOME/.config/git/config" .gitconfig

# Fish
sudo usermod --shell /bin/fish "$USER"
mkdir -p .config/fish

# Nix
sudo mkdir -p /nix/var/nix
sudo chown -R "$USER" /nix
mkdir -p .config/nix
echo 'experimental-features = nix-command flakes' >> .config/nix/nix.conf

# VTerm
echo '
if test "$INSIDE_EMACS" = "vterm"
    and set -q EMACS_VTERM_PATH
    and test -f "$EMACS_VTERM_PATH/etc/emacs-vterm.fish"
    source "$EMACS_VTERM_PATH/etc/emacs-vterm.fish"
end
' >> .config/fish/config.fish

# Direnv
echo 'direnv hook fish | source' >> .config/fish/config.fish

# Emacs
distrobox-export --app emacs
