#+TITLE: My GNU Emacs Configuration
#+AUTHOR: Aiyaz Mostofa

* Introduction
This file is my GNU Emacs configuration, written using Org mode.
I created it by pasting my existing `=init.el=` file into Google Gemini.

** License
[[file:LICENSE][GNU General Public License v3.0]]

* General 
** Speed Up Init Time
This setting is changed at the end.

#+begin_src emacs-lisp :tangle "init.el"
(setq gc-cons-threshold (* 50 1000 1000))
#+end_src

** Must Haves
These are universal in any configuration.

#+begin_src emacs-lisp :tangle "init.el"
(require 'package)
(package-initialize)
(add-to-list
 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'load-path "~/.emacs.d/lisp")
(when (< emacs-major-version 29)
  (unless (package-installed-p 'use-package)
    (unless package-archive-contents
      (package-refresh-contents))
    (package-install 'use-package)))

(setq custom-file "~/.emacs.d/custom.el")
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

** Basic Preferences
General Emacs preferences.

#+begin_src emacs-lisp :tangle "init.el"
(setq
 native-comp-async-report-warnings-errors nil
 auto-save-default nil
 make-backup-files nil
 ring-bell-function 'ignore)

(setq
 inhibit-splash-screen t
 initial-scratch-message ""
 initial-major-mode 'org-mode)
#+end_src

* Ricing (Appearance)
** Basic UI
Hiding UI elements and setting the font.

#+begin_src emacs-lisp :tangle "init.el"
(menu-bar-mode -1)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(when (find-font (font-spec :name "JetBrains Mono"))
  (set-frame-font "JetBrains Mono-16" nil t))
#+end_src

** Display Options
Line truncation and line numbers.

#+begin_src emacs-lisp :tangle "init.el"
(setq-default truncate-lines t)
(global-display-line-numbers-mode)
#+end_src

** Theme
Loading the visual theme.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 ef-themes
 :ensure t
 :config (ef-themes-select 'ef-cyprus))
#+end_src

** Mode Line
Customizing the mode line.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 mostline
 :config (setq-default mode-line-format mostline-format))
#+end_src

* Workflow
** Eshell Integration
Settings and keybindings for the Emacs shell.

#+begin_src emacs-lisp :tangle "init.el"
(defun eshell-buffer-p (buffer)
  (with-current-buffer buffer
    (eq major-mode 'eshell-mode)))
(defun switch-to-eshell-buffer ()
  (interactive)
  (let ((buffers (seq-filter #'eshell-buffer-p (buffer-list))))
    (cond
     ((eq (length buffers) 0)
      (message "No eshell buffers open."))
     ((eq (length buffers) 1)
      (switch-to-buffer (car buffers)))
     (t
      (switch-to-buffer
       (completing-read
        "Switch to eshell buffer: " (mapcar #'buffer-name buffers)
        nil t))))))
(global-set-key (kbd "C-c e") #'switch-to-eshell-buffer)
(global-set-key
 (kbd "C-c E")
 (lambda ()
   (interactive)
   (eshell t)))
(use-package
 eat
 :ensure t
 :config (add-hook 'eshell-load-hook #'eat-eshell-mode))
#+end_src

** Dired Enhancements
Customization for the directory editor.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 dired
 :custom (dired-kill-when-opening-new-dired-buffer t))
#+end_src

** Completion Framework
Vertico and Corfu for enhanced completion.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 orderless
 :ensure t
 :custom (completion-styles '(orderless basic))
 (completion-category-overrides
  '((file (styles partial-completion)))))
(use-package vertico :ensure t :config (vertico-mode 1))
(use-package
 corfu
 :ensure t
 :custom
 (corfu-auto t)
 (corfu-auto-delay 0.01)
 (corfu-auto-prefix 1))
#+end_src

** Version Control
Magit for Git integration.

#+begin_src emacs-lisp :tangle "init.el"
(use-package magit :ensure t :defer t)
#+end_src

** Running Local Scripts
Keybinding to execute `cmd.el`.

#+begin_src emacs-lisp :tangle "init.el"
(global-set-key
 (kbd "C-c c")
 (lambda ()
   (interactive)
   (when (file-exists-p "cmd.el")
     (load-file "cmd.el"))))
#+end_src

* Programming
** Core Programming Features
Treesitter for advanced syntax handling and Yasnippet for templates.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 treesit-auto
 :ensure t
 :custom (treesit-auto-install 'prompt)
 :config
 (treesit-auto-add-to-auto-mode-alist 'all)
 (global-treesit-auto-mode))
(setq
 typescript-ts-mode-indent-offset 4
 tsx-ts-mode-indent-offset 4
 js-ts-mode-indent-offset 4)

(use-package yasnippet :ensure t)
#+end_src

** Language-Specific Enhancements
Settings for Elisp and integration with Language Server Protocol (Eglot).

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 elisp-mode
 :init
 (add-hook
  'emacs-lisp-mode-hook
  (lambda ()
    (electric-pair-local-mode 1)
    (yas-minor-mode 1)
    (rainbow-delimiters-mode 1)
    (corfu-mode 1))))

(use-package
 eglot
 :ensure t
 :init (setq eglot-autoshutdown t)
 :config (setf (plist-get eglot-events-buffer-config :size) 0)
 (add-hook
  'eglot-managed-mode-hook
  (lambda ()
    (interactive)
    (electric-pair-local-mode 1)
    (rainbow-delimiters-mode 1)
    (yas-minor-mode 1)
    (corfu-mode 1)))
 :hook
 ((c-ts-mode
   c++-ts-mode
   go-ts-mode
   python-ts-mode
   typescript-ts-mode
   tsx-ts-mode
   js-ts-mode
   html-ts-mode
   css-ts-mode)
  . eglot-ensure)
 :custom
 (eglot-ignored-server-capabilities
  '(:documentOnTypeFormattingProvider))
 :bind
 (:map
  eglot-mode-map
  ("C-c r" . eglot-rename)
  ("C-c f" . eglot-format)
  ("C-c a" . eglot-code-actions)
  ("C-c D" . xref-find-definitions)
  ("C-c R" . xref-find-references)))

(use-package
 eglot-booster
 :vc
 (:url "https://github.com/jdtsmith/eglot-booster.git" :rev :newest)
 :after eglot
 :config (eglot-booster-mode))

(use-package
 elisp-autofmt
 :ensure t
 :commands (elisp-autofmt-buffer)
 :bind
 (:map
  emacs-lisp-mode-map
  ("C-c f" .
   (lambda ()
     (interactive)
     (message "Formatting...")
     (elisp-autofmt-buffer)))
  ("C-c D" . xref-find-definitions) ("C-c R" . xref-find-references)))

(use-package rainbow-delimiters :ensure t)
#+end_src

** Copeforces
Competitive programming support.

#+begin_src emacs-lisp :tangle "init.el"
(use-package copeforces :bind (("C-c C" . copeforces)))
#+end_src

* Evil Mode/Spacemaster
** Window Management
Custom function for killing windows.

#+begin_src emacs-lisp :tangle "init.el"
(defun kill-window-possibly-buffer ()
  "Kill the current window.
If the buffer associated with the window is not in any other window, kill it too."
  (interactive)
  (if (eq (length (window-list)) 1)
      (if (eq (length (get-buffer-window-list)) 1)
          (kill-current-buffer))
    (if (eq (length (get-buffer-window-list)) 1)
        (kill-buffer-and-window)
      (delete-window))))
#+end_src

** Evil Mode Configuration
Settings for the Evil text editing layer.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 evil
 :ensure t
 :init (setq evil-undo-system 'undo-redo)
 :config (evil-mode 1)
 (evil-define-key
  '(normal visual motion)
  'global
  (kbd "q")
  'kill-window-possibly-buffer)
 (evil-define-key 'insert 'global (kbd "C-n") nil (kbd "C-p") nil)
 (evil-define-key
  'insert
  eshell-mode-map
  (kbd "C-p")
  'eshell-previous-matching-input-from-input
  (kbd "C-n")
  'eshell-next-matching-input-from-input))

#+end_src

** Escape Key Settings
Set escape to quit to make life easier (Evil context)

#+begin_src emacs-lisp :tangle "init.el"
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
(use-package
 transient
 :config
 (define-key transient-map (kbd "<escape>") 'transient-quit-one))
#+end_src

** Spacemaster Configuration
Settings for the Spacemaster keybinding framework.

#+begin_src emacs-lisp :tangle "init.el"
(use-package
 spacemaster
 :config
 (evil-define-key
  '(normal visual motion)
  'global
  (kbd "C-SPC")
  'execute-extended-command
  (kbd "SPC")
  'spacemaster))

(use-package
 dired
 :config (define-key dired-mode-map (kbd "SPC") 'spacemaster))
#+end_src

* Ending
Reset gc to a more normal level
#+begin_src emacs-lisp :tangle "init.el"
(setq gc-cons-threshold (* 2 1000 1000))
#+end_src
